


# 启动时是否打印配置参数
PrintConfig = true

[Log]
# 日志级别(1:fatal 2:error,3:warn,4:info,5:debug)
Level = 5
# 日志格式（支持输出格式：text/json）
Format = "text"
# 日志输出(支持：stdout/stderr/file)
Output = "stdout"
# 指定日志输出的文件路径
OutputFile = "logs/gin_admin.log"


